spring:
  datasource:
    url: "${MYSQL_URL:jdbc:mysql://localhost:3306/algolog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:algolog}
    password: ${MYSQL_PASSWORD:algolog}

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}

logging:
  level:
    org.hibernate.SQL: info

algolog:
  jwt:
    secret: ${JWT_SECRET}
